title: Qâ€™s Logs
description: Public engineering notes by Q
markdown: kramdown
theme: minima
url: "https://logs.marqui.org/"
baseurl: ""
defaults:
  - scope:
      path: "notes"
    values:
      layout: "note"
plugins:
  - jekyll-sitemap

