title: Qâ€™s Logs
description: Public engineering notes by Q
markdown: kramdown
theme: minima
url: "https://marqui.org"
baseurl: "/blog"
defaults:
  - scope:
      path: "notes"
    values:
      layout: "note"
plugins:
  - jekyll-sitemap

